# Generated by Django 5.1.3 on 2024-11-06 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Qr information')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faollik holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'QRCode',
                'verbose_name_plural': 'QrCode',
                'db_table': 'QR kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='F.I.Sh')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('role', models.CharField(blank=True, choices=[('user', 'Oddiy foydalanuvchi'), ('cashier', 'Kassir'), ('admin', 'Admin')], default='user', max_length=100, null=True, verbose_name='Foydalanuvchi roli')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('joined_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 6, 13, 7, 7, 941520), null=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
    ]
