# Generated by Django 5.1.3 on 2024-11-06 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'QRCode', 'verbose_name_plural': 'QR kodlar'},
        ),
        migrations.AlterField(
            model_name='users',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 6, 13, 11, 56, 335682), null=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterModelTable(
            name='qrcode',
            table='QrCode',
        ),
    ]
