# Generated by Django 5.1.3 on 2024-11-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qrcode',
            table='qrcode',
        ),
    ]
