# Generated by Django 5.1.3 on 2024-11-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcode', '0002_alter_qrcode_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='user_name',
            field=models.CharField(blank=True, max_length=221, null=True, verbose_name='QR kod egasi ismi'),
        ),
    ]
